//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsFormsGG102_S_Ana.OgreniIsleri.OgrEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Departments()
        {
            this.tblOgrenciBilgileri = new HashSet<tblOgrenciBilgileri>();
        }
    
        public int Id { get; set; }
        public string BolumAdi { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciBilgileri> tblOgrenciBilgileri { get; set; }
    }
}
