//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsFormsGG102_S_Ana.OgreniIsleri.OgrEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciBilgileri
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tcno { get; set; }
        public string OgnNo { get; set; }
        public Nullable<int> Bolumid { get; set; }
        public Nullable<int> Sehirid { get; set; }
    
        public virtual tbl_Departments tbl_Departments { get; set; }
        public virtual tblSehirler tblSehirler { get; set; }
    }
}
